server:
  port: 8081
#person:
#    lastName: hello
#    age: 18
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: v1,k2: 12}
#    lists:
#      - lisi
#      - zhaoliu
#    dog:
#      name: 小狗
#      age: 12
logging:
  level:
    com.haoge: debug
  path: /spring/log
  pattern:
    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n"
    console: "%d{yyyy/MM/dd} [%thread] %-5level %logger{50} - %msg%n"
    